In [224]:
import os
import logging
from typing import List
import h5py
import numpy as np
import allel

#from utils.io import read_vcf_file

In [70]:
#path1 = '/home/users/miriambt/my_work/dog-gen-to-phen/Datafix/merged_819/imputed_query.npy'

path1 = '/scratch/users/miriambt/data/dogs/formatted_data/4th_dataset/merged/whole_embark_filtered_samples_379_separated.npy'
vcf_path1 = '/scratch/users/miriambt/data/dogs/formatted_data/4th_dataset/merged/whole_embark_filtered_samples_379.vcf'

# 1 indicates the feature is correct and 0 otherwise
path_removed_indexes = '/home/users/miriambt/my_work/dog-gen-to-phen/Datafix/merged_819/'

In [210]:
def read_vcf_file(input_path: str) -> dict:
    """
    Reads data .vcf file.
    
    Args:
        input_path (str): path to .vcf file.
        logger (logging.Logger): debug/information tracker.
        
    Returns:
        data (Dict): dictionary with the content of .vcf file. If the input_path
        is None, then returns None.

    """
    
    if input_path is not None:
        # Read the .vcf file using skikit-allel
        data = allel.read_vcf(input_path)
        
        # Obtain dimensions of the data
        # That is, the amount of samples and of SNPs
        print(f'There are {len(data["variants/ID"])} SNPs and {len(data["samples"])} '\
                    f'samples in {input_path}.')
    else:
        data = None
    
    return data

In [211]:
data1 = np.load(path1)
query = read_vcf_file(vcf_path1)
#removed_indexes = np.load(path_removed_indexes)

There are 185465 SNPs and 379 samples in /scratch/users/miriambt/data/dogs/formatted_data/4th_dataset/merged/whole_embark_filtered_samples_379.vcf.


In [212]:
# Obtain SNPs data
snps = query['calldata/GT']

# Obtain the dimensions of the data
num_snps, num_samples, num_strands = snps.shape

In [213]:
snps

array([[[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[1, 1],
        [1, 1],
        [1, 1],
        ...,
        [1, 1],
        [1, 1],
        [1, 1]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       ...,

       [[0, 1],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[1, 0],
        [0, 1],
        [1, 1],
        ...,
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 0],
        [0, 1],
        [1, 1],
        ...,
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int8)

In [214]:
snps[:,:,0].T

array([[0, 1, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 1],
       ...,
       [0, 1, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 1, 1]], dtype=int8)

In [215]:
snps[:,:,1].T

array([[0, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 1, 1],
       ...,
       [0, 1, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 1, 1]], dtype=int8)

In [216]:
snps_flattened = snps.reshape(num_snps, num_samples*2).T

In [217]:
a = np.ones((num_snps, num_samples, 2))

In [219]:
a[:,:,0] = snps_flattened[::2,:].T
a[:,:,1] = snps_flattened[1::2,:].T

In [222]:
a[:,:,0].T

array([[0., 1., 0., ..., 0., 1., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 1., 1.],
       ...,
       [0., 1., 0., ..., 0., 1., 1.],
       [0., 1., 0., ..., 0., 1., 1.],
       [0., 1., 0., ..., 0., 1., 1.]])

In [223]:
a[:,:,1].T

array([[0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 1.],
       [0., 1., 0., ..., 0., 1., 1.],
       ...,
       [0., 1., 0., ..., 0., 1., 1.],
       [0., 1., 0., ..., 0., 1., 1.],
       [0., 1., 0., ..., 0., 1., 1.]])

In [191]:
a

array([[[0., 0.],
        [1., 1.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       ...,

       [[1., 1.],
        [0., 0.],
        [0., 1.],
        ...,
        [1., 1.],
        [1., 1.],
        [0., 0.]],

       [[1., 1.],
        [0., 0.],
        [1., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 1.],
        [0., 1.],
        [0., 0.],
        ...,
        [0., 0.],
        [1., 1.],
        [1., 1.]]])

In [59]:
def select_snps(vcf_data: dict, indexes: List) -> dict:
    """
    Selects the SNPs at the specified index positions.
    
    Args:
        vcf_data (dict): allel.read_vcf output.
        indexes (List): list with the indexes of the SNPs to be kept. 
                        The SNPs that are not in this list will be removed.
    
    Returns:
        vcf_data (dict): vcf_data containing the SNPs at the specified indexes.
    
    """

    # Keep all the SNPs at the specified index positions for all the keys different from samples
    for key in vcf_data.keys():
        if key != 'samples':
            vcf_data[key] = vcf_data[key][indexes]

    return vcf_data

In [60]:
a = np.ones(len(query["variants/ID"]))

In [61]:
a[[0,1]] = 1
a = a.astype(bool)

In [62]:
query_filtered = select_snps(query, a)

{'samples': array(['140447_S11', '149323_S6', '152721_S5', '160822_S4', '164612_S9',
        '165414_S20', '168979_S18', '171515_S19', '172281_S2',
        '172384_S14', '172724_S8', '173006_S10', '173486_S3', '175885_S12',
        '87125_S1', '91072_S13', '91317_S7', 'AC023', 'AM007',
        'AND10232010_S17', 'AfghanHound01', 'AfghanHound03',
        'AfghanHound04', 'AiredaleTerrier01', 'AiredaleTerrier02',
        'AiredaleTerrier05', 'AlaskanMalamute01', 'AlaskanMalamute02',
        'AustralianCattleDog01', 'AustralianCattleDog02',
        'AustralianCattleDog03', 'BAN00032', 'BAN00041', 'BAN00079',
        'BAN00127', 'BAN00133', 'BAN00136', 'BAN00150', 'BAN00183',
        'BAN00235', 'BAN00283', 'BAN00289', 'BAN00315', 'BAN00368',
        'BAN00380', 'BAN00437', 'BAN00449', 'BAN00461', 'BC0480', 'BC485',
        'BC518', 'BC597', 'BT1021', 'Basenji01', 'Basenji02', 'Basenji03',
        'Beagle01', 'Beagle02', 'Beagle03', 'Beagle04', 'BeardedCollie01',
        'BeardedCollie02',